/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false src/env.d.ts` (hash: d1afb39ba9b704f1f476f6e2d94766a2)
interface __BaseEnv_Env {
	ARTIFACTS: R2Bucket;
	CT_PRINCIPALS: string;
	WORKSPACES: DurableObjectNamespace<import("./index").Workspace>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "Workspace";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CT_PRINCIPALS">> {}
}
