/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false src/env.d.ts` (hash: 05e9738606a683b7e6551c5baad31729)
interface __BaseEnv_Env {
	ARTIFACTS: R2Bucket;
	WORKER_VERSION: WorkerVersionMetadata;
	CT_PRINCIPALS: string;
	WORKSPACES: DurableObjectNamespace<import("./index").Workspace>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "Workspace";
	}
	interface StagingEnv {
		ARTIFACTS: R2Bucket;
		WORKER_VERSION: WorkerVersionMetadata;
		CT_PRINCIPALS: string;
		WORKSPACES: DurableObjectNamespace<import("./index").Workspace>;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CT_PRINCIPALS">> {}
}
