"""Copy the bounded shared Pydantic contract source into the Python Worker.

Models remain owned by packages/core. Empty package initializers deliberately
exclude host-only convenience exports (ingestion adapters and local authority).
No schema generation or duplicate model definitions are involved.
"""

from __future__ import annotations

import ast
import hashlib
import json
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "packages/core/src/coding_trajectory"
DESTINATION = ROOT / "cloudflare/control-plane/src/coding_trajectory"
MODULES = (
    "contracts/__init__.py",
    "contracts/base.py",
    "contracts/envelope.py",
    "contracts/living.py",
    "contracts/prepared_api.py",
    "contracts/registry.py",
    "contracts/session.py",
    "control_plane/collector_protocol.py",
    "control_plane/artifact_protocol.py",
    "control_plane/fact_constants.py",
    "ingestion/common.py",
)


def main():
    sources = {name: (SOURCE / name).read_bytes() for name in MODULES}
    # Fail closed when a contract acquires another repository dependency.
    included = {
        "coding_trajectory." + p.removesuffix(".py").replace("/", ".") for p in MODULES
    }
    included.add("coding_trajectory.contracts")
    for name, body in sources.items():
        for node in ast.walk(ast.parse(body)):
            if (
                isinstance(node, ast.ImportFrom)
                and node.module
                and node.module.startswith("coding_trajectory.")
                and node.module not in included
            ):
                raise ValueError(
                    f"unbundled contract dependency in {name}: {node.module}"
                )
    if DESTINATION.exists():
        shutil.rmtree(DESTINATION)
    for package in ("", "control_plane", "ingestion"):
        path = DESTINATION / package / "__init__.py"
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(
            '"""Shared Worker contract package; generated by bundle-worker-contracts.py."""\n'
        )
    for name, body in sources.items():
        path = DESTINATION / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(body)
    manifest = {
        name: hashlib.sha256(body).hexdigest() for name, body in sources.items()
    }
    (DESTINATION / "sources.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n"
    )
    print(f"Bundled {len(sources)} shared Python contract modules")


if __name__ == "__main__":
    main()
