#!/usr/bin/env python3
"""Generate deterministic Datahub route schemas and TypeScript contracts."""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PLUGIN = ROOT / "packages/plugins/datahub"
WEB = PLUGIN / "web"
SCHEMA = WEB / "src/api/schema/datahub-api.schema.json"
TYPES = WEB / "src/api/generated/datahub-api.ts"
sys.path.insert(0, str(PLUGIN))

from datahub_plugin.api_models import (  # noqa: E402 - repository-local imports after sys.path setup
    API_RESPONSE_MODELS,
    DELIVERY_FAMILIES,
)


def render_schema() -> str:
    definitions: dict[str, object] = {}
    for model in API_RESPONSE_MODELS:
        model_schema = model.model_json_schema(
            mode="serialization", ref_template="#/$defs/{model}"
        )
        nested = model_schema.pop("$defs", {})
        for name, definition in nested.items():
            existing = definitions.get(name)
            if existing is not None and existing != definition:
                raise RuntimeError(f"conflicting JSON Schema definition: {name}")
            definitions[name] = definition
        definitions[model.__name__] = model_schema
    schema = {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "title": "DatahubApiContracts",
        "type": "object",
        "properties": {
            model.__name__: {"$ref": f"#/$defs/{model.__name__}"}
            for model in API_RESPONSE_MODELS
        },
        "$defs": definitions,
    }
    return json.dumps(schema, indent=2, sort_keys=True) + "\n"


def generate() -> tuple[str, str]:
    schema = render_schema()
    with tempfile.TemporaryDirectory() as directory:
        source = Path(directory) / "schema.json"
        target = Path(directory) / "types.ts"
        source.write_text(schema)
        subprocess.run(
            [str(WEB / "node_modules/.bin/json2ts"), "--bannerComment", "/* Generated by scripts/generate-datahub-api-types.py. Do not edit. */", "--unreachableDefinitions", "-o", str(target), str(source)],
            check=True,
            cwd=WEB,
        )
        types = target.read_text()
    family = " | ".join(json.dumps(value) for value in DELIVERY_FAMILIES)
    types += f"\nexport type DeliveryFamily = {family};\n"
    return schema, types


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    schema, types = generate()
    if args.check:
        stale = [path for path, expected in ((SCHEMA, schema), (TYPES, types)) if not path.exists() or path.read_text() != expected]
        if stale:
            print("stale generated Datahub API files: " + ", ".join(str(path.relative_to(ROOT)) for path in stale), file=sys.stderr)
            return 1
        return 0
    for path, content in ((SCHEMA, schema), (TYPES, types)):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
